version: '3'

volumes:
  kittygram_pg_data:
  kittygram_static:
  kittygram_media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - kittygram_static:/backend_static/
      - kittygram_media:/app/media/

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - kittygram_static:/frontend_static/

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - kittygram_static:/static/
      - kittygram_media:/app/media/
    ports:
      - 9000:80
